before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_DEV")
  - ssh-add <(echo "$SSH_PRIVATE_KEY_PROD")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_HOSTKEYS" > ~/.ssh/known_hosts'

dev:
  script:
    - rsync --exclude=.gitlab-ci.yml --exclude=.git -avx -e ssh `pwd`/ dbasdev@iaas.ouce.ox.ac.uk:/var/www/html/it_dev/paaf/auth/
    - rsync --exclude=.gitlab-ci.yml --exclude=.git -avx -e ssh `pwd`/ dbasdev@iaas.ouce.ox.ac.uk:/var/www/html/dbas_dev/main/auth/
    - ssh dbasdev@iaas.ouce.ox.ac.uk /usr/local/bin/restore_dbconfig
  only:
    - dev
    
production:
  script:
    - rsync --exclude=.gitlab-ci.yml --exclude=.git -avx -e ssh `pwd`/ dbas@iaas.ouce.ox.ac.uk:/var/www/html/it_dev/paaf/auth/
    - rsync --exclude=.gitlab-ci.yml --exclude=.git -avx -e ssh `pwd`/ dbas@iaas.ouce.ox.ac.uk:/var/www/html/dbas/main/auth/
    - ssh dbas@iaas.ouce.ox.ac.uk /usr/local/bin/restore_dbconfig
  only:
    - master

